vim.opt.termguicolors = true
vim.opt.number = true
vim.opt.wrap = true
vim.opt.relativenumber = true
vim.opt.cursorline = true
vim.opt.expandtab = false
vim.opt.smarttab = true
vim.opt.shiftwidth = 2
vim.opt.softtabstop = 2
vim.opt.autoindent = true
vim.opt.scrolloff = 4
vim.opt.foldmethod = 'indent'
vim.opt.foldlevel = 99
vim.opt.foldenable = true
vim.opt.foldlevelstart = 99
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.showmode = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.signcolumn = "yes"
vim.opt.mouse:append("a")
vim.opt.clipboard:append("unnamedplus")

-- vim.o.ttyfast = true
-- vim.o.autochdir = true
-- vim.o.exrc = true
-- vim.o.secure = false
-- vim.o.tabstop = 2
-- vim.o.list = true
-- vim.o.listchars = 'tab:|\\ ,trail:▫'
-- vim.o.ttimeoutlen = 0
-- vim.o.timeout = false
-- vim.o.viewoptions = 'cursor,folds,slash,unix'
-- vim.o.textwidth = 0
-- vim.o.indentexpr = ''
-- vim.o.formatoptions = vim.o.formatoptions:gsub('tc', '')
-- vim.o.shortmess = vim.o.shortmess .. 'c'
-- vim.o.inccommand = 'split'
-- vim.o.completeopt = 'longest,noinsert,menuone,noselect,preview'
-- vim.o.completeopt = 'menuone,noinsert,noselect,preview'
-- -- vim.o.lazyredraw = true
-- vim.o.visualbell = true
-- vim.o.colorcolumn = '100'
-- vim.o.updatetime = 100
-- vim.o.virtualedit = 'block'
