export ZSH="$HOME/.oh-my-zsh"
export PATH=$PATH:/home/xwx/.local/bin
ZSH_THEME="geoffgarside"
plugins=(git zsh-syntax-highlighting zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

#alias
alias n="nvim"
alias ra="ranger"
alias condaE="source ~/Code/dotfile/scripts/condaEnable"
alias cax="conda activate xwx"
alias cls="clear"
alias pc="proxychains"

# exec
# eval "$(atuin init zsh)"
# eval "$(oh-my-posh init --config ~/.config/tokyo.omp.json zsh)"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/xwx/.conda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/xwx/.conda/etc/profile.d/conda.sh" ]; then
        . "/home/xwx/.conda/etc/profile.d/conda.sh"
    else
        export PATH="/home/xwx/.conda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

