export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="geoffgarside"
plugins=(git zsh-syntax-highlighting zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

#alias
alias n="nvim"
alias ra="yazi"
alias yz="yazi"
alias condaE="source ~/Code/dotfile/scripts/condaEnable"
alias cax="conda activate xwx"
alias cls="clear"
alias pc="proxychains"
# Env
export EDITOR="nvim"
export PATH=$PATH:$HOME/.local/bin
