local v = vim
v.opt.termguicolors = true
v.opt.number = true
v.opt.wrap = true
v.opt.relativenumber = true
v.opt.cursorline = true
v.opt.expandtab = false
v.opt.smarttab = true
v.opt.shiftwidth = 2
v.opt.softtabstop = 2
v.opt.autoindent = true
v.opt.scrolloff = 4
v.opt.foldmethod = 'indent'
v.opt.foldlevel = 99
v.opt.foldenable = true
v.opt.foldlevelstart = 99
v.opt.splitright = true
v.opt.splitbelow = true
v.opt.showmode = true
v.opt.ignorecase = true
v.opt.smartcase = true
v.opt.signcolumn = "yes"
v.opt.mouse:append("a")
v.opt.clipboard:append("unnamedplus")

-- vim.o.ttyfast = true
-- vim.o.autochdir = true
-- vim.o.exrc = true
-- vim.o.secure = false
-- vim.o.tabstop = 2
-- vim.o.list = true
-- vim.o.listchars = 'tab:|\\ ,trail:▫'
-- vim.o.ttimeoutlen = 0
-- vim.o.timeout = false
-- vim.o.viewoptions = 'cursor,folds,slash,unix'
-- vim.o.textwidth = 0
-- vim.o.indentexpr = ''
-- vim.o.formatoptions = vim.o.formatoptions:gsub('tc', '')
-- vim.o.shortmess = vim.o.shortmess .. 'c'
-- vim.o.inccommand = 'split'
-- vim.o.completeopt = 'longest,noinsert,menuone,noselect,preview'
-- vim.o.completeopt = 'menuone,noinsert,noselect,preview'
-- -- vim.o.lazyredraw = true
-- vim.o.visualbell = true
-- vim.o.colorcolumn = '100'
-- vim.o.updatetime = 100
-- vim.o.virtualedit = 'block'
