#!/bin/bash
if [ $# == 1 ]
then
        m --profile=bili-live \
	    https://live.bilibili.com/"$1"
elif [ $# == 3 ] && [ "$2" == '-r' ]
then
	time=$(date "+%m%d%H%M%S")
        filename="/home/xwx/Media/Live/${3}-${time}.flv"
        echo "Record in ~/Media/Live/"
        m --profile=bili-live \
	    --stream-record="${filename}" \
            https://live.bilibili.com/"$1" 
elif [ $# > 2 ] && [ "$2" == '-a' ]
then
        m --profile=bili-live \
            https://live.bilibili.com/"$1" \
	    "${*:3}"
else
        echo "bili-live:Wrong Arg!"
fi
