#!/bin/bash
# Tip="Fetching..."
# printf "\e[35m%s\e[0m\n" $Tip
cid=$(curl -s https://api.bilibili.com/x/player/pagelist?bvid="$1"\
  | jq '.["data"][0]["cid"]')


if [ $# == 1 ]; then
	echo $cid $1
  m --profile=bili-v --script-opts=cid=$cid \
    https://www.bilibili.com/$1
elif [ $# == 3 ] && [ $1 == 'p' ]; then
  prefix="https://www.bilibili.com/video/${2}/?p="
  num=$3
  sum=""
  for i in `seq 1 ${num}`; do
	  sum="${sum}${prefix}${i} "
  done	
  mpv.exe --profile=bili-v ${sum}
else
  echo Wrong Arg!!
fi
