#!/bin/bash
clashconfig=$(cat ~/.clash/current)
wget -O /home/xwx/.clash/${clashconfig}.yaml $(cat /home/xwx/.clash/.${clashconfig}.link)
if [[ ${clashconfig} == 'ikuuu' ]] ;then
  sed -i -e '/socks-port/s/7891/7890/g' /home/xwx/.clash/${clashconfig}.yaml && \
    echo 'Doing: sed -i -e "'"/socks-port/s/7891/7890/g"'" /home/xwx/.clash/${clashconfig}.yaml'
  sed -i -e '/socks-port/s/socks/mixed/g' /home/xwx/.clash/${clashconfig}.yaml && \
    echo 'Doing: sed -i -e "'"/socks-port/s/socks/mixed/g"'" /home/xwx/.clash/${clashconfig}.yaml'
  sed -i -e '/^port/d' /home/xwx/.clash/${clashconfig}.yaml && \
    echo 'Doing: sed -i -e "'"/^port/d"'" /home/xwx/.clash/${clashconfig}.yaml'
  head -n 1 /home/xwx/.clash/${clashconfig}.yaml
fi
echo Update ${clashconfig}!
sudo systemctl daemon-reload && sudo systemctl restart clash
