#!/bin/bash
xrandr \
 --dpi 144 \
 --output eDP-1 --mode 2560x1600 --rate 120 --pos 0x0 --primary \
 --output HDMI-1 --off \
 --output DP-1 --off \
 --output DP-2 --off \
 --output DP-3 --off \
 --output DP-4 --off

echo "Xft.dpi: 144" | xrdb -merge

feh --bg-fill --no-fehbg --randomize ~/Media/wallpaper/
