#!/bin/bash
xrandr \
 --dpi 144 \
 --output eDP-1 --off \
 --output $1 --mode 2560x1440 --rate 60 --pos 0x0 --primary \

echo "Xft.dpi: 144" | xrdb -merge

feh --bg-fill --no-fehbg --randomize ~/Media/wallpaper/
