#!/bin/bash
xrandr \
 --dpi 128 \
 --output eDP-1 --off \
 --output $1 --mode 1920x1080 --rate 75 --pos 0x0 --primary \

echo "Xft.dpi: 128" | xrdb -merge

feh --bg-fill --no-fehbg --randomize ~/Media/Picture/wallpaper/wallpaper/
