#!/bin/bash
vname="${1}"".mp4"
sname="${1}"".ass"
if [ `sudo envycontrol -q` == 'integrated' ]
then
  para=''
else
  para='-hwaccel cuda'
fi
echo video:
cat video
echo subtitle:
cat sub
echo ffmpeg "$para" -f concat -safe 0 -i video -c copy "${1}.mp4"
echo ffmpeg "$para" -f concat -safe 0 -i sub "${1}.ass"
echo ffmpeg "$para" -i $vname -i $sname -c copy "${1}.mkv"
echo Is That Right? Enter to GO ON or Ctrl-C to Exit...
read
echo "ffmpeg "$para" -f concat -safe 0 -i video -c copy "${1}.flv" -y && \
      ffmpeg "$para" -f concat -safe 0 -i sub "${1}.ass" -y && \
      ffmpeg "$para" -i $vname -i $sname -c copy "${1}.mkv" -y " | sh
