#!/bin/bash
# fcitx5
export LANG=zh_CN.UTF-8
export GTK_IM_MODULE DEFAULT=fcitx
export QT_IM_MODULE  DEFAULT=fcitx
export XMODIFIERS    DEFAULT=\@im=fcitx

# CapsLock&Escape
xmodmap ~/.Xmodmap

# dpi
xrdb -merge ~/.Xresources

# exec
fcitx5 -d &
lsusb --verbose &
