#!/bin/bash
HDMI=`xrandr | grep -E 'HDMI-1' | awk -F' ' '{ print $2 }'`
DP=`xrandr | grep -E '^DP-1' | awk -F' ' '{ print $2 }'`

# fcitx5
export LANG=zh_CN.UTF-8
export GTK_IM_MODULE DEFAULT=fcitx
export QT_IM_MODULE  DEFAULT=fcitx
export XMODIFIERS    DEFAULT=\@im=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus


# dpi
# xrdb -merge ~/.Xresources
#
# if [[ $HDMI == 'connected' ]]; then
#    xrdb -merge <<< Xft.dpi:128
# else
#    xrdb -merge <<< Xft.dpi:144
# fi

# exec

# CapsLock&Escape
# xmodmap ~/.Xmodmap
