#!/bin/bash

cmd='mpv.exe'
opt=''

params=""
urls=""

for arg in "$@"; do
  if [[ $arg == http* ]]; then
    urls+=" $arg"
  elif [[ $arg == *=* ]]; then
    if [[ $arg != --* ]]; then
      arg="--$arg"
    fi
    params+=" $arg"
  else
    echo "Unknown Arg: $arg" >&2
    exit 1
  fi
done

exec 1> /dev/null
echo "exec $cmd$params$urls" | bash
