#!/bin/bash
if [[ $# == 0 ]]; then
  echo Nothing Input!
  exit
fi

state=`sudo envycontrol -q`
cmd='mpv'
opt=''

while [ $# != 0 ]; do
  add="$1"
  if [[ $add == *"="* && $add != "--"* ]];then
    add="--$add"
  fi
  opt="$opt"" $add"
  shift
done

nv_nl=$(lspci -nnk | grep -n '01:00.0' | awk -F: '{print $1}')
nv_dri=$(lspci -nnk | awk 'NR=='$((nv_nl + 2))' {print $5}')
bat_stat=$(upower -i `upower -e | grep 'BAT'` | awk '/state/{print $2}')

if [[ $nv_dri != 'integrated' ]] && [[ $bat_stat != 'discharging' ]]; then
  cmd="$cmd ""$opt"
else
  cmd="$cmd ""--profile=intel""$opt"
fi

echo exec $cmd
