#!/bin/bash

module_nl=$(grep -E "^MODULES=" /etc/mkinitcpio.conf -n | awk -F: '{print $1}')
grub_nl=$(grep -E "GRUB_CMDLINE_LINUX_DEFAULT=" /etc/default/grub -n | awk -F: '{print $1}')


if [[ $1 == 'v' ]]; then
  sudo  sed -i ''$module_nl'c MODULES=(xhci_hcd vfio_pci vfio vfio_iommu_type1)' /etc/mkinitcpio.conf
  sudo  sed -i ''$grub_nl'c GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet intel_iommu=on iommu=pt rd.driver.pre=vfio-pci video=efifb:off vfio-pci.ids=10de:25a9"' /etc/default/grub
elif [[ $1 == 'n' ]]; then
  sudo sed -i ''$module_nl'c MODULES=(xhci_hcd)' /etc/mkinitcpio.conf
  sudo sed -i ''$grub_nl'c GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet"' /etc/default/grub
fi
awk 'NR=='$module_nl' {print $0}' /etc/mkinitcpio.conf
awk 'NR=='$grub_nl' {print $0}' /etc/default/grub

if [[ $2 == 'yes' ]]; then
  sudo mkinitcpio -P
  sudo grub-mkconfig -o /boot/grub/grub.cfg
  sudo reboot
  exit 0
else
  read -p "grub-updata? [y/N] " opt
  if [[ $opt == 'Y' || $opt == 'y' ]]; then
    sudo mkinitcpio -P
    sudo grub-mkconfig -o /boot/grub/grub.cfg
    read -p "reboot? [y/N] " opt
    if [[ $opt == 'Y' || $opt == 'y' ]]; then
      sudo reboot
    fi
  fi
fi
